site_name: "Get Security Done"

nav:
    - About this Project: 'README.md'
    - Assumed Knowledge: 'AssumedKnowledge.md'
    - Full project in one Page: 'GSD.md'
    - Microsoft Defender for Identity (MDI): 'MDI.md'
    - Conditional Access (CA): 'CondAccess.md'
    - Microsoft Defender for Cloud Apps (MDAC): 'MDAC.md'
    - Microsoft Defender for Endpoint (MDE): 'MDE.md'
    - Microsoft Defender for Office (MDO): 'MDO.md'
    - Microsoft Information Protection (MIP/AIP): 'MIP.md'
    - Microsoft Sentinel Content: 'Sentinel.md'
    - Ninja Security Training Content: 'Ninja.md'
    - Security Interactive Guides & Product Trials: 'Guides.md'
    #
    #
    - Partner Content: 'partner.md'

# Configuration
theme:
  name: material
#  custom_dir: !ENV [THEME_DIR, "material"]
# Default values, taken from mkdocs_theme.yml
  features:
    # - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      # primary: red
      # accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  # font:
  #  text: Roboto
  #  code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
# Plugins
plugins:
    - search
    - simple
    #- social
    #- awesome-list
    #- table-reader
    #- img2fig
    #- mermaid2
    - macros
    # - minify
# Customization
extra:
  analytics:
    provider: google
    property: G-QS5J5W9G3Q
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dcaddick/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dcaddick
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/dcaddick/
