site_name: "Get Security Done"
plugins:
- simple:
- search:
# - awesome-list:
# - table-reader:
# - mermaid2:

theme:
  features:
  #  - navigation.tabs
  #  - navigation.tabs.sticky
  #  - navigation.instant
  
theme:
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
    - About this Project: 'README.md'
    - Full project in one Page: 'GSD.md'
    - Microsoft Defender for Identity (MDI): 'MDI.md'
    - Conditional Access (CA): 'CondAccess.md'
    - Microsoft Defender for Cloud Apps (MDAC): 'MDAC.md'
    - Microsoft Defender for Endpoint (MDE): 'MDE.md'
    - Microsoft Defender for Office (MDO): 'MDO.md'
    - Microsoft Sentinel Content: 'Sentinel.md'
    - Ninja Training Content: 'Ninja.md'
    - Interactive Guides & Product Trials: 'Guides.md'
    - Partner Content: 'partner.md'
