site_name: "Get Security Done"
plugins:
- simple:
- search:
# - awesome-list:
# - table-reader:
# - mermaid2:

nav:
    - Introduction: 'index.md'
    - Microsoft Defender for Endpoint (MDE): 'MDE.md'
