site_name: "Get Security Done"
plugins:
- simple:
- search:
# - awesome-list:
# - table-reader:
# - mermaid2:

theme:
  palette:
    primary: green


nav:
    - About this Project: 'README.md'
    - Full project in one Page: 'GSD.md'
    - Microsoft Defender for Identity (MDI): 'MDI.md'
    - Conditional Access (CA): 'CondAccess.md'
    - Microsoft Defender for Cloud Apps (MDAC): 'MDAC.md'
    - Microsoft Defender for Endpoint (MDE): 'MDE.md'
    - Microsoft Defender for Office (MDO): 'MDO.md'
    - Microsoft Sentinel Content: 'Sentinel.md'
    - Ninja Training Content: 'Ninja.md'
    - Interactive Guides & Product Trials: 'Guides.md'
    - Partner Content: 'partner.md'
