name: "Check Links"

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 7 * * *'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: lychee link checker
      uses: lycheeverse/lychee-action@v1.0.9
      with:
        args: --verbose
