name: Links

on:
    push:
    pull_request:
#   repository_dispatch:
#   workflow_dispatch:
#   schedule:
#     - cron: "00 18 * * *"

permissions:
  contents: write
  issues: write  

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.2.0
        with:
          args: --accept '200..=204, 429, 500'

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5.0.1
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
